import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/common/header";
import SideBar from "./components/common/sideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-full">
        <div className="h-full">
          <Header />
          <div className="flex flex-row h-full">
            <SideBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
